# Generated by Django 5.0.6 on 2024-06-04 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('ethereum_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('usdt_rate', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsAndCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, max_length=5000, null=True)),
                ('message2', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin', models.CharField(max_length=150)),
                ('ethereum', models.CharField(max_length=150)),
                ('tether_USDT', models.CharField(max_length=150)),
                ('ERC20_address', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteVisitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_on_card', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('deposits', models.CharField(blank=True, default='Deposits', editable=False, max_length=10, verbose_name='deposits')),
                ('deposits_day_one', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('deposits_day_two', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('deposits_day_three', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('deposits_day_four', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('deposits_day_five', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('profits', models.CharField(blank=True, default='Profits', editable=False, max_length=10, verbose_name='profits')),
                ('profits_day_one', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('profits_day_two', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('profits_day_three', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('profits_day_four', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('profits_day_five', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('losses', models.CharField(blank=True, default='Profits', editable=False, max_length=10, verbose_name='losses')),
                ('losses_day_one', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('losses_day_two', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('losses_day_three', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('losses_day_four', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('losses_day_five', models.CharField(blank=True, default=0, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoBalances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_balance', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('ethereum_balance', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('usdt_balance', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('card_number', models.CharField(blank=True, max_length=100, null=True)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField(blank=True, null=True)),
                ('available_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True)),
                ('card_status', models.CharField(choices=[('Not activated', 'Not activated'), ('Activated', 'Activated'), ('Blocked', 'Blocked')], default='Not activated', max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True)),
                ('network', models.CharField(blank=True, max_length=100, null=True)),
                ('proof', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('status', models.CharField(choices=[('No deposit', 'No Deposit'), ('Failed', 'Failed'), ('Under review', 'Under review'), ('Confirmed', 'Confirmed')], default='', max_length=50)),
                ('status_message', models.TextField(blank=True, max_length=5000, null=True)),
                ('requestID', models.CharField(blank=True, default='', max_length=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IDME',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('id_front', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('id_back', models.ImageField(blank=True, null=True, upload_to='id_cards/')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('micro', 'Micro'), ('standard', 'Standard'), ('premium', 'Premium'), ('elite', 'Elite'), ('premium-yields', 'Premium Yields'), ('Signatory', 'Signatory')], default='micro', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration', models.CharField(max_length=100)),
                ('waiver', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='awaiting slot entry', max_length=100)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='is_verified',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('verification_code', models.IntegerField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MinimumDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Welcome!!', max_length=100)),
                ('message', models.TextField(default='Welcome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bitcoin_address', models.CharField(blank=True, max_length=255, null=True)),
                ('ethereum_address', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_TRC20_address', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_ERC20_address', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_login', models.BooleanField(default=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('deposits', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=10.0, max_digits=10)),
                ('profits', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10)),
                ('account_manager', models.CharField(blank=True, default='not assigned', max_length=255)),
                ('withdrawal_limit', models.DecimalField(decimal_places=2, default=7000.0, max_digits=10)),
                ('pin', models.IntegerField(default=0)),
                ('can_withraw', models.BooleanField(default=False)),
                ('trade_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Completed', 'Completed'), ('Canceled', 'Canceled'), ('No Trade', 'No Trade')], default='No Trade', max_length=30)),
                ('verification_status', models.CharField(choices=[('Verified', 'Verified'), ('Failed', 'Failed'), ('Under review', 'Under Review'), ('Awaiting', 'Awaiting')], default='awaiting', max_length=50)),
                ('alert_user', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='send_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=255, null=True)),
                ('Message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(default='no data', max_length=100)),
                ('address', models.CharField(default='no data', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Under review', 'Under review'), ('Failed', 'Failed'), ('Approved', 'Approved')], default='Checking', max_length=30)),
                ('status_message', models.TextField(blank=True, max_length=5000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('RequestID', models.IntegerField(blank=True, default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
