# Generated by Django 5.0.6 on 2024-06-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinox', '0002_exchangerates_termsandcondition_walletaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
