# Generated by Django 5.0.6 on 2024-06-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinox', '0005_alter_cardrequest_status_alter_investments_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='bnb_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
