# Generated by Django 5.0.6 on 2024-06-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinox', '0006_paymentdetails_bnb_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletaddress',
            old_name='bitcoin',
            new_name='bitcoin_address',
        ),
        migrations.RenameField(
            model_name='walletaddress',
            old_name='ethereum',
            new_name='ethereum_address',
        ),
        migrations.RenameField(
            model_name='walletaddress',
            old_name='ERC20_address',
            new_name='usdt_ERC20_address',
        ),
        migrations.RemoveField(
            model_name='paymentdetails',
            name='bnb_address',
        ),
        migrations.AddField(
            model_name='walletaddress',
            name='bnb_address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
