# Generated by Django 5.0.6 on 2024-06-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinox', '0007_rename_bitcoin_walletaddress_bitcoin_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investments',
            name='debit_account',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='investments',
            name='reference',
            field=models.CharField(default='', max_length=30),
        ),
    ]
