# Generated by Django 5.0.6 on 2024-06-14 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equinox', '0008_investments_debit_account_investments_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charts',
            name='user',
        ),
        migrations.DeleteModel(
            name='TermsAndCondition',
        ),
        migrations.DeleteModel(
            name='Charts',
        ),
    ]
