# Generated by Django 5.0.6 on 2024-06-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equinox', '0009_remove_charts_user_delete_termsandcondition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='verification_status',
            field=models.CharField(choices=[('Under review', 'Under Review'), ('Verified', 'Verified'), ('Failed', 'Failed'), ('Awaiting', 'Awaiting')], default='Awaiting', max_length=50),
        ),
    ]
